language: objective-c
xcode_workspace: iOS-Template.xcworkspace
xcode_scheme: Staging
osx_image: xcode7
before_install:
- export LANG=en_US.UTF-8
- sudo gem install cocoapods --no-document
- chmod +x ./scripts/travis/add-key.sh
- chmod +x ./scripts/travis/remove-key.sh
- chmod +x ./scripts/travis/sign-and-upload.sh
install:
- pod install
script:
- ./iOS-Template/Scripts/build.sh
before_script:
- ./scripts/travis/add-key.sh
after_script:
- ./scripts/travis/remove-key.sh
after_success:
- ./scripts/travis/sign-and-upload.sh
env:
  global:
  - APPNAME="iOS-Template"
  - 'DEVELOPER_NAME="iPhone Distribution: Juan Balarini (5U87XMD88S)"'
  - PROFILE_NAME="TestDistributionProfileFS"
  - secure: q5mBRL+VEhHYHy6e+qFdpzf4As9hw975iXWgq4+egnrYmLvbCUluAJj8PmHONLWvTy7fnYaAWiUYD8ViFcOQOWj4MsRMWYeu0COm6pp3BsTYsPMyUcZ5OuwIVgXvyayHv+0P7th4GJzkP6jy932UWJi5YWJRuyTx0ApAs4qJy+bjNxJmiAQoYdTdXD+ZQIA86qjuad+ItVxBv3ZScvTlHaRBRYS0EF6T+jVvRSXFKRIDgYyz7lAmPVI6DRyRIz+SUAZ3DPafmKh25MDuuFI0/MgpzZ5KoXUnCpPfaXlwbtHFAz3jQMSRK/p0n2ty+RCfoZZjO776cLjdDfbPE1YzW7CWbMqtntQ2upwrCukZ1vRigSdGlO52/fwKBfqFDuhmIpX2uhCzjyfLFHrX31EOlZUZiayHTgV9M1AE2pSrLTdanS2sSQA2ruXck/aZLbm7IahDcEYsNTb4NxjhBeId5YVJrtoFOv0VWzLgIDPnLONsuUvdCi8ue9WqzY6JBx/oW/8kKJCYj/p/OwJL5pkERBbnw9ln2ZsRAgK8CJZdIEvJCsC0C/XX8ZY2We4c5Mbg2yQON9C+LaA7lOuZegsl2emImyPk/wE3z7gCU1kIRqtJMphH075HKEUAP1KrLNz3llU5N+fwcgcBwfQ/7nTnws+W60pUewklkmafu2BPUYk=
  - secure: QXVVbkcGvRLrkKF8McSOdgxXCesfDUSQ4JdnZjogE4i5Cyf5ddy9O2AGLn26Bx1+E3hdCpQM8R9zuS81//PyGsjk4xw0O3zfgylEDvE2guaKXCYOcg2KJPgLRHN4p0FdbS1NLrcrG7YAbvin439PFrlETy+I+XxtPb1Ztsd33aX6lBAqP/fn1ODZaJJV7NSphugTzqOWTLaUhW20+5HR3Ug8a7mnBLfKdqiGTrKLh8BUHXXuVWECi1MGB0PnO+UIM/It3JVFhJg0jwuU/6aI7AfL922RpdKNzHiz9D5Bd3ZBrTen8aicC+xsmrdQJhu9NAe9dTPR6d/2Jx/qKWVoskk+FsSRyFxJTGCv3iU1jWoMmX8DR+PuQzxBTr/vIc9kGV1B2Ifg1UB2d4qnVDS9rwaw5jMrwwr2ub8PFu1h3TsJUjVEgvFvS3fRqB1PqFUZLStNJWvnhH5dLeMlj/fpy4w8iq8vaO9w44O3o6Azo5H74z+TzaWaqRkn4QsxP3gIm8+F83OjRyiJUBvhhmrILge+xygPBo+s7Dv578HZU1rIVGjCaIISMCnO1H5EuN1xcnTjXqmVS0WMTFEvidNNkBedQYlFNd9MHSJEYtCfP7S1W1kPpQc5cGx9CbwFgXAdsZ2K6mhHqeOUP84jFgtpje0yJtSNF4oe6b27WEgT37E=
  - secure: diBwQ3HVv0UuCJE1tobYL12ahc8sTImKRy24iP9HmsYVuKhyqWNP0bwtbud1D1sSGZDeH1xnszgBzwug5ZbSbkS4+xHlGWUAlI5Wv4byvBlJOtCP0FRhlNBojrTxngrEsDJWROs3RFf7Cq/f9LS/qXjo6lsWF41HfL1LYbFiv4m5E3rItRmIKmZVdHr0+glugCaGlRBhVzPgAbpJP4TWEQz7iS0clF9tObKSB3VAFu2ISQCNlGp89NJKGXQaaZYpBPXQYGiwblnfXtUMS+9XY7wKddMID+032P6mDAwmcGpwKKkM5XDEcRytcbEVDubf5sG/h1pJXN5IS64daXnT3A0zNO84BYVk2w4yeqlMsNbqdjETCklDGf4FuTZB3UnuP9KaJyqEYljSCxbqR7cbp08TqgvjjIrsTuhzAipjf2tdaFHYIijlMN43RtxC95D8V5h3uPion3x5Eb72J8teziputYcVxTIfscLoXexHE9PK+LMOF1WCfhWaUORs6jPOPzhdmiaVWTBKok7ZPVY88g186iOPvQrWQc5iU956sjoDXjrIRuue17eSNX+pvZ46bh7grP2DOhbop36Uu5qBL1SdDvGfL0zECTgdDopGit0Q5mHXUuiLnYL7++IlrgHv1eaD80jjYxg0n+Zki5GCzT+JXE9FLAPrSVeKP5m7eSc=
notifications:
  hipchat:
    rooms:
    - $API_TOKEN@ios-base
  email:
    recipients: 
    on_success: change
    on_failure: always
