language: objective-c
xcode_workspace: iOS-Template.xcworkspace
xcode_scheme: Staging
osx_image: xcode7
before_install:
- export LANG=en_US.UTF-8
- sudo gem install cocoapods --no-document
- chmod +x ./scripts/travis/add-key.sh
- chmod +x ./scripts/travis/remove-key.sh
- chmod +x ./scripts/travis/sign-and-upload.sh
install:
- pod install
script:
- ./iOS-Template/Scripts/build.sh
before_script:
- ./scripts/travis/add-key.sh
after_script:
- ./scripts/travis/remove-key.sh
after_success:
- ./scripts/travis/sign-and-upload.sh
env:
  global:
  - APPNAME="iOS-Template"
  - 'DEVELOPER_NAME="iPhone Distribution: Juan Balarini (5U87XMD88S)"'
  - PROFILE_NAME="TestDistributionProfileFS"
notifications:
  hipchat:
    rooms:
    - $API_TOKEN@ios-base
  email:
    recipients:
    on_success: change
    on_failure: always
